import { readFile, writeFile, mkdir, rm, copyFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const load = async name => JSON.parse(await readFile(resolve(root, 'content', name + '.json'), 'utf8'));
const [chapters, faq, cases] = await Promise.all(['chapters', 'faq', 'cases'].map(load));
const requestedBase = process.env.SITE_BASE || '/';
if (!/^\/(?:[a-zA-Z0-9_-]+\/)*$/.test(requestedBase)) throw new Error('SITE_BASE 必须是 / 或 /项目名/');
const base = requestedBase;
const url = path => base + path.replace(/^\//, '');
const repo = 'https://github.com/Tiee7/dot-green-book';
const dotGuide = 'https://dot.1idea.xyz/';
const showcase = 'https://dot.1idea.xyz/showcase/';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const paras = value => String(value).split(/\n+/).filter(Boolean).map(x => `<p>${esc(x)}</p>`).join('');
const list = values => `<ul>${values.map(x => `<li>${esc(x)}</li>`).join('')}</ul>`;
const officialLabels = { 'dots':'认识 Dot', 'getting-started':'开始使用', 'controls':'控制与停止', 'computers-and-apps':'电脑与应用', 'channels':'消息渠道', 'tasks-and-memory':'任务与记忆' };
const sources = urls => `<div class="sources"><span>继续核对</span>${[...new Set(urls)].map(link => `<a href="${esc(link)}" target="_blank" rel="noreferrer">${esc(officialLabels[link.split('/').at(-1)?.split('#')[0]] || '官方说明')} ↗</a>`).join('')}</div>`;
const prompt = (text, id) => `<div class="prompt-box"><div class="prompt-top"><span>试着这样交代</span><button type="button" data-copy="${esc(id)}">复制指令</button></div><pre id="${esc(id)}">${esc(text)}</pre></div>`;
const nav = [{p:'learn/',t:'循序渐进'}, {p:'faq/',t:'问答手册'}, {p:'cases/',t:'Dot 案例'}, {p:'about/',t:'关于与共建'}];
function layout(title, description, content, active = '', { reader = false, path = '' } = {}) {
  const current = `${title} · Dot小绿皮书`;
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#eef3eb"><meta property="og:title" content="${esc(current)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><title>${esc(current)}</title><link rel="icon" href="${url('favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${url('site.css')}"><script src="${url('site.js')}" defer></script></head><body data-base="${esc(base)}"><a class="skip" href="#main">跳到正文</a><header class="header"><div class="header-inner"><a class="brand" href="${base}"><span class="book-mark" aria-hidden="true">书</span><span>Dot小绿皮书</span></a><nav class="desktop-nav" aria-label="主导航">${nav.map(x=>`<a href="${url(x.p)}" ${active===x.p?'aria-current="page"':''}>${x.t}</a>`).join('')}</nav><a class="github" href="${repo}" target="_blank" rel="noreferrer">GitHub ↗</a><details class="mobile-menu"><summary>目录</summary><nav aria-label="移动导航">${nav.map(x=>`<a href="${url(x.p)}">${x.t}</a>`).join('')}</nav></details></div></header><main id="main" class="${reader?'reader-main':'wrap'}">${content}</main><footer class="footer wrap"><div><a class="footer-brand" href="${base}">Dot小绿皮书</a><p>把一个小任务做好，再交给 Dot 一份持续的责任。</p></div><div><a href="${url('about/')}#sources">来源与评分</a><a href="${repo}/blob/main/CONTRIBUTING.md" target="_blank" rel="noreferrer">一起写这本书 ↗</a><a href="${dotGuide}" target="_blank" rel="noreferrer">dot-guide 在线阅读 ↗</a><a href="${showcase}" target="_blank" rel="noreferrer">持续更新的 Showcase ↗</a></div></footer><div class="toast" role="status" aria-live="polite"></div></body></html>`;
}
const crumb = name => `<div class="breadcrumb"><a href="${base}">首页</a><span>/</span><span>${esc(name)}</span></div>`;
const chapterRows = chapters.map((c,i)=>`<a class="chapter-row" href="${url(`learn/${c.id}/`)}"><span class="chapter-number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(c.title)}</h3><p>${esc(c.subtitle)}</p></div><span class="chapter-meta">${esc(c.level)} · 建议 ${c.minutes} 分钟</span><span class="row-arrow" aria-hidden="true">↗</span><span class="complete-label" data-complete-id="${esc(c.id)}"></span></a>`).join('');
const caseCard = c => `<article class="case-card" data-search="${esc([c.title,c.category,c.summary,c.author].join(' ').toLowerCase())}" data-category="${esc(c.category)}"><div class="case-top"><span>${esc(c.category)}</span><span class="score">${c.score}<small>/10</small></span></div><h2><a href="${url(`cases/${c.id}/`)}">${esc(c.title)}</a></h2><p>${esc(c.summary)}</p><div class="case-bottom"><span>${esc(c.author)}</span><a href="${url(`cases/${c.id}/`)}">读这个案例 ↗</a></div><span class="evidence-tag">${c.verification==='source-reviewed'?'原帖已核对':'上游整理 · 待复核'} · 编辑学习价值评分</span></article>`;

const output = resolve(root, 'dist');
await rm(output, {recursive:true, force:true});
await mkdir(output, {recursive:true});
async function emit(path, title, description, body, active, opts={}) { const file=resolve(output,path,'index.html'); await mkdir(dirname(file),{recursive:true}); await writeFile(file,layout(title,description,body,active,{...opts,path})); }

await emit('', '从第一次交代，到持续协作', '8章渐进教程、实用问答与编辑学习价值8分及以上的Dot用户案例。一起学会使用ChatGPT Dot。', `
<section class="hero"><div class="hero-copy"><p class="eyebrow">一本会继续生长的开源使用手册</p><h1>和 Dot 一起，<br>把下一步做好。</h1><p class="hero-description">从第一次交代任务，到长期跟进一件事。<br>循序渐进，学会和你的 ChatGPT Dot 协作。</p><div class="hero-actions"><a class="button primary" href="${url(`learn/${chapters[0].id}/`)}">从第一章开始 <span aria-hidden="true">↗</span></a><a class="text-link" href="${url('cases/')}" >看看大家怎么用</a></div></div><div class="cover" aria-label="Dot小绿皮书封面"><div class="cover-spine"></div><div class="cover-face"><span class="cover-small">THE DOT GREEN BOOK</span><span class="cover-title">Dot<br>小绿皮书</span><span class="cover-rule"></span><p>认识 · 交代 · 连接 · 跟进<br>检查 · 纠错 · 继续</p><span class="cover-bottom">一份持续更新的中文协作手册</span></div></div></section>
<div class="book-stats"><span><strong>${chapters.length}</strong> 章渐进教程</span><span><strong>${faq.length}</strong> 个实用问答</span><span><strong>${cases.length}</strong> 个精选 Dot 案例</span><span>产品事实核对 <strong class="date">2026.10.01</strong></span></div>
<section class="home-learning"><div class="section-heading"><h2>先学一小步，再做一小步。</h2><p>每章都有可复制的指令、练习和验收清单。阅读时间是建议，不是任务完成承诺。</p></div><div class="learning-layout"><aside class="learning-note"><h3>这本书怎么读？</h3><p>第一次接触 Dot，从第一章开始。已经在使用，可以带着一个问题直接翻到对应章节。</p><a href="${url('learn/')}" class="text-link">展开完整学习路线 ↗</a><div class="progress-note" data-progress>阅读进度保存在当前浏览器。</div></aside><div class="chapter-list">${chapterRows}</div></div></section>
<section class="faq-preview"><div><h2>遇到问题，先翻一下。</h2><p>找不到入口、资料读不到、跟进没发生？<br>把现象说清楚，就能一步步检查。</p><a class="button secondary" href="${url('faq/')}">打开问答手册 ↗</a></div><div>${faq.slice(0,4).map(q=>`<a class="question-link" href="${url('faq/')}#${q.id}">${esc(q.question)}<span aria-hidden="true">↗</span></a>`).join('')}</div></section>
<section class="home-cases"><div class="section-heading"><h2>从真实用户的一件事开始。</h2><p>只收录明确来自 Dot 的公开用户分享。8 分指编辑学习价值，查看案例可了解证据和限制。</p></div><div class="case-grid">${cases.slice(0,3).map(caseCard).join('')}</div><a class="text-link more-link" href="${url('cases/')}">阅读全部 ${cases.length} 个案例 ↗</a><p class="online-update">想继续发现新作品？访问 <a href="${dotGuide}" target="_blank" rel="noreferrer">dot-guide 在线阅读 ↗</a>，或浏览 <a href="${showcase}" target="_blank" rel="noreferrer">持续更新的 Showcase ↗</a>。</p></section>
<section class="contribute"><div><h2>把你的经验，写进下一页。</h2><p>一个有来源的案例，一条更清楚的回答，一次产品变化的纠正，都能让这本书更好用。</p></div><a class="button primary" href="${repo}/issues/new/choose" target="_blank" rel="noreferrer">提交问题或案例 ↗</a></section>`);

await emit('learn','循序渐进','从认识Dot到建立个人工作流程，按8章学习并实践。', `${crumb('循序渐进')}<div class="page-heading"><p class="eyebrow">先完成练习，再扩大责任</p><h1>八章，走完第一次协作。</h1><p>每章只解决一个核心问题。打开一章，照着做，再检查结果。</p></div><div class="route-note"><p><strong>还没看到 Dot 入口？</strong>先读第一章的可用性检查。可以先学习交代方式；本教程无法替你的账号开通 Dot。</p><span data-progress></span></div><div class="chapter-list full-list">${chapterRows}</div><button class="reset-progress" type="button" data-reset-progress>清除本机阅读进度</button>`,'learn/');

for (const [i,c] of chapters.entries()) {
 const toc = chapters.map((v,j)=>`<a href="${url(`learn/${v.id}/`)}" ${c.id===v.id?'aria-current="page"':''}><span>${String(j+1).padStart(2,'0')}</span>${esc(v.title)}</a>`).join('');
 const next=chapters[i+1],prev=chapters[i-1];
 await emit(`learn/${c.id}`,c.title,c.subtitle,`<div class="reader-layout"><aside class="toc"><a class="toc-title" href="${url('learn/')}">学习路线</a><nav aria-label="章节目录">${toc}</nav><p data-progress></p></aside><article class="reading">${crumb(c.title)}<div class="reading-heading"><p class="eyebrow">第 ${i+1} 章 · ${esc(c.level)} · 建议 ${c.minutes} 分钟</p><h1>${esc(c.title)}</h1><p class="lead">${esc(c.intro)}</p></div>${c.sections.map(s=>`<section><h2>${esc(s.title)}</h2>${paras(s.body)}</section>`).join('')}<section><h2>跟着做一次</h2><ol class="steps">${c.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${prompt(c.prompt,`prompt-${c.id}`)}<p class="exercise-label">这是改编的教学练习，尚未替你执行；请按实际账户和材料调整。</p></section><section class="check-section"><h2>做到这里，怎么验收？</h2>${c.checks.map((s,j)=>`<label class="check"><input type="checkbox" data-check="${esc(c.id)}-${j}"><span>${esc(s)}</span></label>`).join('')}<button class="button secondary" type="button" data-mark-complete="${esc(c.id)}">标记本章已完成</button><p class="small">标记由你自行确认，仅记录在当前浏览器；不是 Dot 任务的自动验收结果。</p></section><section class="pitfalls"><h2>先避开这两个坑</h2>${list(c.pitfalls)}</section>${sources(c.sourceUrls)}<nav class="chapter-pagination" aria-label="相邻章节">${prev?`<a href="${url(`learn/${prev.id}/`)}">← 上一章<br><strong>${esc(prev.title)}</strong></a>`:`<a href="${url('learn/')}">← 完整目录</a>`}${next?`<a href="${url(`learn/${next.id}/`)}">下一章 →<br><strong>${esc(next.title)}</strong></a>`:`<a href="${url('cases/')}">去读 Dot 案例 →</a>`}</nav></article></div>`,'learn/',{reader:true});
}

const faqCategories=[...new Set(faq.map(q=>q.category))];
await emit('faq','问答手册',`${faq.length}个ChatGPT Dot常见问题，按主题搜索、定位和排查。`,`${crumb('问答手册')}<div class="page-heading"><h1>你遇到的，可能也在这里。</h1><p>${faq.length} 个具体问题。每个回答都给出一个可以继续做的动作。</p></div><section class="search-section" data-filter-group><label class="search-label" for="faq-search">搜索问题或关键词</label><div class="search-line"><input type="search" id="faq-search" data-search-input placeholder="试试：暂停、电脑、邮件、记忆" autocomplete="off"><span class="search-hint">按 / 搜索</span></div><div class="filters" role="group" aria-label="问答分类"><button type="button" data-filter="all" aria-pressed="true">全部</button>${faqCategories.map(c=>`<button type="button" data-filter="${esc(c)}" aria-pressed="false">${esc(c)}</button>`).join('')}</div><p class="result-count" aria-live="polite" data-result-count>共 ${faq.length} 个问题</p><div class="faq-list">${faq.map(q=>`<details class="faq-item" id="${q.id}" data-category="${esc(q.category)}" data-search="${esc([q.question,q.answer,q.action].join(' ').toLowerCase())}"><summary><span class="faq-category">${esc(q.category)}</span><h2>${esc(q.question)}</h2><span class="disclosure-icon" aria-hidden="true">+</span></summary><div class="answer">${paras(q.answer)}<p class="next-action"><strong>接下来：</strong>${esc(q.action)}</p><div class="answer-bottom"><a href="${url(`learn/${q.chapterId}/`)}">读对应章节 ↗</a><a href="#${q.id}" aria-label="${esc(q.question)}的直达链接">直达此问题</a></div>${sources(q.sourceUrls)}</div></details>`).join('')}</div><div class="empty-state" data-empty hidden><h2>暂时没有找到这个问题。</h2><p>换一个关键词，或清除分类再试试。</p><button class="button secondary" data-clear-filter type="button">显示全部问题</button></div></section>`,'faq/');

const categories=[...new Set(cases.map(c=>c.category))];
await emit('cases','Dot案例',`只收录编辑学习价值8分及以上的ChatGPT Dot用户案例，保留原帖、证据与限制。`,`${crumb('Dot 案例')}<div class="page-heading"><p class="eyebrow">从一件具体的事，学一种协作方式</p><h1>别人把什么交给了 Dot？</h1><p>精选 ${cases.length} 个公开用户案例。看目标、过程和结果，也看证据能支持到哪一步。</p></div><div class="case-note"><p><strong>这里的 8 分是什么？</strong>它是本项目的编辑学习价值评分，不是作者评分、官方认证或任务成功率。所有练习指令均为教学改编。</p><a href="${url('about/')}#scoring">查看收录与评分标准 ↗</a><p>更多在线更新的作品见 <a href="${showcase}" target="_blank" rel="noreferrer">Showcase ↗</a>。本书仅收录逐条核对 Dot 归属与原帖的精选案例；展厅更新不代表本书已完成新案例审查。</p></div><section data-filter-group><label class="search-label" for="cases-search">搜索案例</label><div class="search-line"><input id="cases-search" type="search" data-search-input placeholder="试试：邮件、创作、资料研究" autocomplete="off"></div><div class="filters" role="group" aria-label="案例分类"><button type="button" data-filter="all" aria-pressed="true">全部</button>${categories.map(c=>`<button type="button" data-filter="${esc(c)}" aria-pressed="false">${esc(c)}</button>`).join('')}</div><p class="result-count" data-result-count aria-live="polite">共 ${cases.length} 个案例</p><div class="case-grid">${cases.map(caseCard).join('')}</div><div class="empty-state" data-empty hidden><h2>没有匹配的案例。</h2><button type="button" class="button secondary" data-clear-filter>显示全部案例</button></div></section>`,'cases/');

const scoreLabels={goal:'目标清晰',workflow:'过程可学习',result:'结果具体',evidence:'证据充分',transfer:'迁移价值'};
for (const c of cases) await emit(`cases/${c.id}`,c.title,c.summary,`<article class="reading case-reading">${crumb('Dot 案例')}<a class="back-link" href="${url('cases/')}">← 返回案例库</a><div class="reading-heading"><p class="eyebrow">${esc(c.category)} · ${esc(c.author)}</p><h1>${esc(c.title)}</h1><p class="lead">${esc(c.summary)}</p></div><div class="case-source-line"><span>编辑学习价值 <strong>${c.score}/10</strong></span><a class="button secondary" href="${esc(c.sourceUrl)}" target="_blank" rel="noreferrer">查看用户原帖 ↗</a></div><section><h2>Dot 接住了哪一步？</h2>${paras(c.dotRole)}</section><section><h2>原作者描述的结果</h2>${paras(c.outcome)}</section><section class="evidence-section"><h2>证据支持到哪一步？</h2>${paras(c.evidence)}${paras(c.limits)}<p class="small">${c.verification==='source-reviewed'?'本轮原帖核对':'来自上游整理，尚未完成本轮原帖核对'} · ${esc(c.checkedAt)}${c.date?` · 原帖日期：${esc(c.date)}`:''}</p></section><section><h2>你可以怎样学习这个做法？</h2><p>${esc(c.lesson)}</p><ol class="steps">${c.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${prompt(c.prompt,`case-prompt-${c.id}`)}<p class="exercise-label">以上步骤与指令是本书的教学改编，不是原作者逐字提示词，也不是已经完成的实测。</p></section><section><h2>为什么收录？</h2><div class="score-grid">${Object.entries(c.scores).map(([key,value])=>`<div><span>${scoreLabels[key]}</span><strong>${value}/2</strong></div>`).join('')}</div><a href="${url('about/')}#scoring" class="text-link">了解评分标准 ↗</a></section></article>`,'cases/');

await emit('about','关于与共建','Dot小绿皮书的内容来源、案例评分规则和开源贡献方式。',`<article class="reading about-reading">${crumb('关于与共建')}<div class="reading-heading"><h1>一本小书，持续校对。</h1><p class="lead">让中文用户能从第一次交代任务开始，逐步学会使用 ChatGPT Dot。先说清楚，再动手做；先检查一件事，再扩大责任。</p></div><section><h2>这本书从哪里来？</h2><p>本项目参考私人闭源项目 <strong>dot-guide</strong> 的内容主题与来源整理，重新编写为开源中文渐进教程。新项目独立维护，原仓库保留原状。dot-guide 的源码仓库不对公众开放，公开阅读入口是 <a href="${dotGuide}" target="_blank" rel="noreferrer">dot.1idea.xyz ↗</a>。</p><p>想持续跟进新作品，可以浏览 <a href="${showcase}" target="_blank" rel="noreferrer">在线更新的 Showcase ↗</a>。该展厅包含不同产品的作品；本书仍逐条核对 Dot 归属、原帖与证据后收录。</p><p>教程围绕 Dot 的持续协作、连接资料、任务委派和跟进方式展开。案例库只收录明确来自 Dot 的用户分享；普通模型生成案例和归属混杂的演示不进入本书精选。</p></section><section id="sources"><h2>三种内容，三种读法</h2><dl class="definition-list"><dt>产品事实</dt><dd>以本页链接的官方说明为依据，核对日期为 2026-10-01。账户、地域、版本和组织权限仍以你看到的界面及最新官方文档为准。</dd><dt>公开用户案例</dt><dd>标注原作者和原帖。核对原帖能确认作者的说法，不能独立证明生成过程、准确性、耗时或效果。本书没有把作者自述包装成独立复现。</dd><dt>教学练习</dt><dd>为学习重新编写的指令、步骤和验收清单。需要你在自己的 Dot 里运行，练习本身不代表成功结果。</dd></dl>${sources(['https://learn.chatgpt.com/docs/dots','https://learn.chatgpt.com/docs/dots/getting-started','https://learn.chatgpt.com/docs/dots/controls','https://learn.chatgpt.com/docs/dots/computers-and-apps','https://learn.chatgpt.com/docs/dots/channels','https://learn.chatgpt.com/docs/dots/tasks-and-memory'])}</section><section id="scoring"><h2>8 分及以上，怎样评？</h2><p>评分衡量案例作为学习材料的价值，由编辑按五项分别给 0 至 2 分，总分 10 分。只有明确的 Dot 用户案例且总分至少 8 分才进入精选。分数不是 OpenAI 官方评分，也不代表通用性能或成功率。</p><table class="scoring-table"><thead><tr><th>项目</th><th>0 分</th><th>1 分</th><th>2 分</th></tr></thead><tbody><tr><th>目标清晰</th><td>没有任务目标</td><td>仅说明大方向</td><td>有具体问题与场景</td></tr><tr><th>过程可学习</th><td>只有赞美</td><td>能看出主要动作</td><td>能看出多步协作或交接</td></tr><tr><th>结果具体</th><td>未说明结果</td><td>有具体结果自述</td><td>有可见成果或明确后续行动</td></tr><tr><th>证据充分</th><td>无原始来源或归属不明</td><td>原作者明确自述使用 Dot</td><td>原帖另有可检查的相关输出</td></tr><tr><th>迁移价值</th><td>无法转为练习</td><td>可借鉴单一步骤</td><td>可整理成目标、权限与验收</td></tr></tbody></table><p>尚未核对原帖、只展示情绪评价、缺少具体任务结果，或把不同产品的贡献混在一起时，暂不进入精选。失败案例仍可帮助改进教程，记入来源审查记录。</p><a href="${repo}/blob/main/docs/case-review.md" target="_blank" rel="noreferrer">查看案例审查记录 ↗</a></section><section><h2>怎样参与共建？</h2><ol class="steps"><li>提交问题：描述你看到的界面、操作和期待的结果，先去除个人信息。</li><li>提交 Dot 案例：给出原帖或脱敏记录，说明 Dot 的具体任务、可见结果和限制。</li><li>修正产品变化：附官方链接、核对日期和受影响的章节。</li></ol><p>代码与本项目原创教程采用 MIT 许可证。第三方原帖及其媒体版权归原作者；本书保留来源链接，不把第三方作品重新授权。</p><a class="button primary" href="${repo}/issues/new/choose" target="_blank" rel="noreferrer">一起写下一页 ↗</a></section><section><h2>本书记录什么？</h2><p>网站没有账号、分析统计或第三方脚本。你手动标记的阅读进度和验收勾选保存在当前浏览器，可以在目录页清除；不会上传到本项目。</p><p>研究、发消息、发布、购买和修改资料的实际授权与执行结果，应在你的 Dot 任务里核对。</p></section></article>`,'about/');

for (const file of ['site.css','site.js','favicon.svg']) await copyFile(resolve(root,file),resolve(output,file));
await writeFile(resolve(output,'.nojekyll'),'');
await writeFile(resolve(output,'404.html'),layout('这一页还没有写到','返回Dot小绿皮书继续阅读。',`<div class="page-heading"><h1>这一页还没有写到。</h1><p>链接可能改变了，回目录找找看。</p><a class="button primary" href="${url('learn/')}">返回学习路线</a></div>`));
await writeFile(resolve(output,'build-info.json'),JSON.stringify({base,chapters:chapters.length,faq:faq.length,cases:cases.length,checkedAt:'2026-10-01'},null,2));
console.log(`生成完成：${chapters.length}章 / ${faq.length}问答 / ${cases.length}Dot案例，部署路径 ${base}`);
